spring:
  datasource:
    driverClassNam: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/lasa
    username: Rajashekar
    password: Uday1406@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    user:
      name: Shivakumar
      password: shiva@123
server:
  port: 8085
  servlet:
    context-path: /lasa-dev