spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  security:
    user:
      name: Rajashekar
      password: Uday1406@
server:
  port: 8086
  servlet:
    context-path: /lasa-qa