spring:
  application:
    name: LASA
  profiles:
    active: dev
logging:
  level:
    org:
      springframework:
        web: DEBUG
irctc:
  endpoint:
    book_ticket: http://localhost:9090/book
    view_ticket: http://localhost:9090/view
    view_all_ticketS: http://localhost:9090/view/all